when:
  - event: pull_request
  - event: push
    branch: main

steps:
  lint:
    image: valalang/lint:latest
    commands:
      - io.elementary.vala-lint -c vala-lint.conf || exit 1

  build:
    depends_on: [lint]
    image: alpine:edge
    commands:
      - apk add --no-cache meson vala glib-dev gtk4.0-dev json-glib-dev libadwaita-dev libsoup3-dev desktop-file-utils gettext-dev make clang git libsecret-dev glycin-loaders-dev
      - CC=clang make build
