on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  lint:
    name: "Vala Lint"
    runs-on: codeberg-tiny
    steps:
    - uses: actions/checkout@v4
    - uses: elementary/actions/vala-lint@master
      with:
        conf: vala-lint.conf
